[build]
    command = "pnpm build:auto"
    publish = "build"

[build.environment]
    NODE_VERSION = "18.14.0"
    NPM_FLAGS = "-v"
    PUBLIC_TITLE = "SvelteKit Starter"

[functions]
    node_bundler = "esbuild"
