[build]
    command = "npx pnpm i --store-dir=.pnpm && npx pnpm build:auto"
    publish = "build"

[build.environment]
    NODE_VERSION = "18.1.0"
    NPM_FLAGS = "-v"
    PUBLIC_TITLE = "SvelteKit Starter"

[functions]
    node_bundler = "esbuild"
