export { default as Success } from "~icons/fa-solid/check"
export { default as Error } from "~icons/fa-solid/times-circle"
export { default as Warning } from "~icons/fa-solid/exclamation-triangle"
export { default as Info } from "~icons/fa-solid/info-circle"
export { default as Moon } from "~icons/fa-solid/moon"
export { default as Sun } from "~icons/fa-solid/sun"
export { default as Close } from "~icons/fa-solid/times"
export { default as Loading } from "~icons/whh/loadingflowcw"
